<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Models\Commission;

class AffiliateLink extends Model
{
    protected $fillable = [
        'affiliate_id',
        'product_id',
        'link_code',
        'clicks_count',
    ];

    /**
     * Get the affiliate that owns this link.
     */
    public function affiliate(): BelongsTo
    {
        return $this->belongsTo(Affiliate::class);
    }

    /**
     * Get the product associated with this link.
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /**
     * Get all clicks on this link.
     */
    public function clicks(): HasMany
    {
        return $this->hasMany(AffiliateClick::class);
    }
    /**
 * Get all commissions generated by this link.
 */
public function commissions(): HasMany
{
    return $this->hasMany(Commission::class, 'affiliate_link_id');
}
}
